// ___________Variables & Data types________________

// ____________Variable______________
// A variable is used to store a piece of data for processing. It is called a variable because 
//you can change the value stored. 
// 1) A variable has a name (or identifier), e.g., radius, area, age, height.
//  (e.g., radius=1.2),

// 2) A variable has a type. Examples of type are,
// int: for integers (whole numbers) such as 123 and -456;
//double: for floating-point or real numbers such as 3.1416, -55.66, having a decimal point and fractional part.